### ISSUE TITLE
v1.18 failed with config file mounted

### ISSUE THREAD

**Issue by MyDigitalLife** [nginxinc/docker-nginx-unprivileged#37]
I have a project that has nginx in my docker-compose like this:
```
  nginx:
    image: nn-docker.artifactory.prd.ss.aws.insim.biz/nginxinc/nginx-unprivileged:1.18-alpine
    ports:
      - "8081:8081"
    volumes:
    - "./../etc/nginx.conf:/etc/nginx/nginx.conf"
```

But on v1.18 i am getting the following errors:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-configure-nginx-unprivileged.sh
sed: can't move '/etc/nginx/nginx.confMDbjOE' to '/etc/nginx/nginx.conf': Resource busy
```

Going back to version 1.17.x works fine. What is the issue here? Am I configuring something incorrectly or is this a bug?

**Comment by wzrdtales** [comment]
it clearly is a bug...

**Comment by alessfg** [comment]
I'm looking into it a the moment. The simple reason seems to be that the volume mount prevents the last entrypoint script from being run correctly (the entrypoint script should not modify files you've mounted in a volume). Let me try to look into it and see what can be done. 1.17.10 should work for the time being.

**Comment by MattMencel** [comment]
I'm seeing similar behavior all of a sudden in our containers as well.
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Can not modify /etc/nginx/conf.d/default.conf (read-only file system?), exiting
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-configure-nginx-unprivileged.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2020/06/05 14:04:21 [emerg] 1#1: invalid port in "808080" of the "listen" directive in /etc/nginx/conf.d/default.conf:2
nginx: [emerg] invalid port in "808080" of the "listen" directive in /etc/nginx/conf.d/default.conf:2
```

**Comment by MyDigitalLife** [comment]
@MattMencel I think your having a different issue here. Your error is implying that you are using a invalid port. If i'm not mistaken ports are a unsigned 16-bit integer so the highest port number you can use is 65535.

**Comment by ujoergen** [comment]
Seeing both issues. Not sure why the port update to default.conf is done in startup script instead of Docker build?

**Comment by ujoergen** [comment]
In think it is the same issue - if you have port 8080 in your default.conf - it becomes 808080 after the script has run.

**Comment by MattMencel** [comment]
The `default.conf` is updated in our docker build. We see those errors when we run the container in Kubernetes. The pod goes CLB. We saw the errors when we ran `kubectl logs po PODNAME --previous`.

No idea where the 808080 is coming from.... as it's not in any of our build configs.

**Comment by ujoergen** [comment]
I think it is the line:

`sed -i -e '/listen/!b' -e '/80;/!b' -e 's/80;/8080;/' /etc/nginx/conf.d/default.conf \`

in https://github.com/nginxinc/docker-nginx-unprivileged/blob/master/stable/alpine/30-configure-nginx-unprivileged.sh that changes 8080 to 808080 - it also gives us "resource busy" when we run in k8s with a configmap mounted default.conf.

**Comment by alessfg** [comment]
Can I please ask you all test the `nginxinc/nginx-unprivileged:test` image and let me know if that fixed your issues? And if not, can you post your current errors?

I made a couple changes that should fix the original issue (`'/etc/nginx/nginx.conf': Resource busy`), and coincidentally should also fix the port 808080 issue by using stricter `sed` substitutions.

That being said, I have not run into a `resource busy` issue with default.conf in any of my tests, and there should be checks already in place to prevent that from happening. If you are still running into that issue once you check out the test image, can you post your error log?

Finally, the changes are now made in the startup script instead of the main Docker build to accommodate some changes made in the upstream NGINX image (and enable IPv6 by default on IPv6 enabled systems).

**Comment by ujoergen** [comment]
Thank you looking into this. I tested the mounting of configmap in k8s - and still see issue there. I have a mounting snippet like:
`        volumeMounts:
          - name: proxy-nginx-default-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
 `
where the file in the configmap replaces the default.conf.

The other case where we use the image as a base and add default.conf in Dockerfile seems to work with the test image. Not seeing issues with port 808080.

**Comment by btsuhako** [comment]
thanks @alessfg! i built one of our projects with `FROM nginxinc/nginx-unprivileged:test`, the image ran fine as a container with my local Docker. i'll have to test it in Kubernetes

we experienced the same thing in one of our built images recently. we're rolling back to `nginxinc/nginx-unprivileged:1.17` until there's a published fix

**Comment by MattMencel** [comment]
I tested it in kubernetes and it worked for us.

**Comment by alessfg** [comment]
@ujoergen can you share your container logs? And could you by any chance try to run the "normal" NGINX image on your cluster and see if you experience the same error? I am trying to replicate your issue atm but it'd definitely help if I could have a look beforehand (and, it might be an issue that affects the "normal" NGINX image too).

**Comment by alessfg** [comment]
Nice, thanks for the info! I see you are using the `:stable-alpine` tag in your k8s deployment. Did you try to use the `:test` tag and run into the same issue?

At any rate, I'm partially reverting some of the changes while I do some further testing -- aka moving back the unprivileged config changes to the main Dockerfile. The entrypoint scripts won't ever successfully run right now (cue no dynamic IPv6 configs), but at least the images should work in the meantime.

**Comment by ujoergen** [comment]
Tested again with `nginxinc/nginx-unprivileged:test`- and it seems to work now with the test.yml. The container log is:

> /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
> 10-listen-on-ipv6-by-default.sh: Can not modify /etc/nginx/conf.d/default.conf (read-only file system?), exiting
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
> /docker-entrypoint.sh: Configuration complete; ready for start up

**Comment by alessfg** [comment]
Good to know! I'll update this thread once I have a new version of the image to test 😄

**Comment by alessfg** [comment]
I pushed a new version of the images on Monday -- given that I haven't seen any issues reported I'm hoping the issues have been addressed 😄

**Comment by ujoergen** [comment]
Works nicely for us. Thx 👍

**Comment by AllexVeldman** [comment]
With the current 1.18 (`@sha256:73948ceb33ff13d977099d5c2a65faa62f9f04b8b5deea9be8df811a6a81659d`) I get:
```
│ /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration                                                                                                         │
│ /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/                                                                                                                                │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh                                                                                                                    │
│ /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh: 21: /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh: 2: not found                                                                             │
│ stream closed
```

Reverting back to `@sha256:e1b0dc152caec58a182c130532140da5f39a780db554bd6d045830655f99069c` resolved it for me.

Can this be related to this issue?

**Comment by alessfg** [comment]
No, it was a different issue as discussed already in #44 😄

**Comment by ademilua** [comment]
$ docker container run -it -p 40:80 nginx                                          /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

**Comment by ademilua** [comment]
I can find solution to this issue yet from this thread, how to resolve this?

Status: Downloaded newer image for nginx:latest
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

**Comment by alessfg** [comment]
Getting that output is not an error. Looks like your container is starting just fine? You can try to set `NGINX_ENTRYPOINT_QUIET_LOGS` as an environment variable to cancel any stdout messaging when launching a new container.

**Comment by burninmedia** [comment]
If the above is expected should it say "starting up" instead of "ready for start-up"?

**Comment by alessfg** [comment]
I'd leave that feedback on the [`docker-nginx`](https://github.com/nginxinc/docker-nginx) repo -- for the most part this repo merely adapts those Dockerfiles to be functional in unprivileged systems.

**Comment by tpetrow** [comment]
Explicitly adding  CMD [ "/bin/bash", "-c", "nginx -g 'daemon off;'" ] to my Dockerfile helped me to solve the problem.
My configMap with default.conf is now injected correctly.

**Comment by ratulb** [comment]
docker run nginx
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

**Comment by pankaj-dahiya** [comment]
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Configuration complete; ready for start up


I am getting this error with nginx:stable
@alessfg

**Comment by glensc** [comment]
@pankaj-dahiya, @ratulb why are you posting these here? or more precisely what are you reporting? those are diagnostic messages, no error in there. if you have a problem, you should create a new issue with details of what you think is wrong, what do you expect, and what you did not get rather than hijacking closed issues with "me too" responses. this issue is about "Resource busy" error, which neither of you have in the output you've passed!
